# CMake generated Testfile for 
# Source directory: /Users/wu/leveldb_sub/leveldb
# Build directory: /Users/wu/leveldb_sub/leveldb/build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(c_test "/Users/wu/leveldb_sub/leveldb/build/c_test")
set_tests_properties(c_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;341;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(fault_injection_test "/Users/wu/leveldb_sub/leveldb/build/fault_injection_test")
set_tests_properties(fault_injection_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;342;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(issue178_test "/Users/wu/leveldb_sub/leveldb/build/issue178_test")
set_tests_properties(issue178_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;344;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(issue200_test "/Users/wu/leveldb_sub/leveldb/build/issue200_test")
set_tests_properties(issue200_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;345;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(issue320_test "/Users/wu/leveldb_sub/leveldb/build/issue320_test")
set_tests_properties(issue320_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;346;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(env_test "/Users/wu/leveldb_sub/leveldb/build/env_test")
set_tests_properties(env_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;348;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(status_test "/Users/wu/leveldb_sub/leveldb/build/status_test")
set_tests_properties(status_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;349;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(no_destructor_test "/Users/wu/leveldb_sub/leveldb/build/no_destructor_test")
set_tests_properties(no_destructor_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;350;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(autocompact_test "/Users/wu/leveldb_sub/leveldb/build/autocompact_test")
set_tests_properties(autocompact_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;353;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(corruption_test "/Users/wu/leveldb_sub/leveldb/build/corruption_test")
set_tests_properties(corruption_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;354;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(db_test "/Users/wu/leveldb_sub/leveldb/build/db_test")
set_tests_properties(db_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;355;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(dbformat_test "/Users/wu/leveldb_sub/leveldb/build/dbformat_test")
set_tests_properties(dbformat_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;356;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(filename_test "/Users/wu/leveldb_sub/leveldb/build/filename_test")
set_tests_properties(filename_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;357;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(log_test "/Users/wu/leveldb_sub/leveldb/build/log_test")
set_tests_properties(log_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;358;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(recovery_test "/Users/wu/leveldb_sub/leveldb/build/recovery_test")
set_tests_properties(recovery_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;359;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(skiplist_test "/Users/wu/leveldb_sub/leveldb/build/skiplist_test")
set_tests_properties(skiplist_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;360;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(version_edit_test "/Users/wu/leveldb_sub/leveldb/build/version_edit_test")
set_tests_properties(version_edit_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;361;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(version_set_test "/Users/wu/leveldb_sub/leveldb/build/version_set_test")
set_tests_properties(version_set_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;362;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(write_batch_test "/Users/wu/leveldb_sub/leveldb/build/write_batch_test")
set_tests_properties(write_batch_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;363;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(memenv_test "/Users/wu/leveldb_sub/leveldb/build/memenv_test")
set_tests_properties(memenv_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;365;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(filter_block_test "/Users/wu/leveldb_sub/leveldb/build/filter_block_test")
set_tests_properties(filter_block_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;367;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(table_test "/Users/wu/leveldb_sub/leveldb/build/table_test")
set_tests_properties(table_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;368;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(arena_test "/Users/wu/leveldb_sub/leveldb/build/arena_test")
set_tests_properties(arena_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;370;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(bloom_test "/Users/wu/leveldb_sub/leveldb/build/bloom_test")
set_tests_properties(bloom_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;371;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(cache_test "/Users/wu/leveldb_sub/leveldb/build/cache_test")
set_tests_properties(cache_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;372;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(coding_test "/Users/wu/leveldb_sub/leveldb/build/coding_test")
set_tests_properties(coding_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;373;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(crc32c_test "/Users/wu/leveldb_sub/leveldb/build/crc32c_test")
set_tests_properties(crc32c_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;374;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(hash_test "/Users/wu/leveldb_sub/leveldb/build/hash_test")
set_tests_properties(hash_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;375;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(logging_test "/Users/wu/leveldb_sub/leveldb/build/logging_test")
set_tests_properties(logging_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;376;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
add_test(env_posix_test "/Users/wu/leveldb_sub/leveldb/build/env_posix_test")
set_tests_properties(env_posix_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;338;add_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;383;leveldb_test;/Users/wu/leveldb_sub/leveldb/CMakeLists.txt;0;")
subdirs("third_party/googletest")
subdirs("third_party/benchmark")
